CREATE TABLE [dbo].[ComponentScore] (
    [ComponentScoreID]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [UserID]                 BIGINT          NOT NULL,
    [UserName]               NCHAR (100)     NULL,
    [FirstName]              NCHAR (32)      NULL,
    [LastName]               NCHAR (32)      NULL,
    [ProgramTypeID]          INT             NOT NULL,
    [ProgramName]            VARCHAR (64)    NOT NULL,
    [AssessmentTakenDate]    DATETIME        NOT NULL,
    [ConsortiumID]           INT             NULL,
    [ConsortiumName]         NVARCHAR (128)  NULL,
    [InstitutionID]          BIGINT          NULL,
    [InstitutionName]        NVARCHAR (128)  NULL,
    [ActiveClassID]          INT             NULL,
    [ActiveClassName]        NVARCHAR (45)   NULL,
    [TestingClassID]         INT             NULL,
    [TestingClassName]       NVARCHAR (45)   NULL,
    [ContentAreaID]          INT             NOT NULL,
    [ContentAreaName]        NVARCHAR (100)  NULL,
    [AssessmentID]           INT             NULL,
    [AssessmentName]         NVARCHAR (128)  NULL,
    [TestAttempt]            INT             NOT NULL,
    [AdjPercentage]          DECIMAL (12, 2) NULL,
    [RawScore]               FLOAT (53)      NULL,
    [ProgramMean]            DECIMAL (12, 2) NULL,
    [TestAttemptID]          BIGINT          NOT NULL,
    [PendingAssessmentCount] INT             NOT NULL,
    [IsFinalScore]           BIT             NULL,
    [BatchID]                INT             NULL,
    [DateCreated]            SMALLDATETIME   CONSTRAINT [DF__Component__DateC__6B24EA82] DEFAULT (getdate()) NULL,
    [UserCreated]            NVARCHAR (30)   CONSTRAINT [DF_ComponentScore_UserCreated] DEFAULT (N'SYSUSER') NULL,
    [DateModified]           DATETIME        NULL,
    [UserModified]           NVARCHAR (30)   NULL,
    [SourceSystemID]         INT             NULL,
    [SourceDateCreated]      DATETIME        CONSTRAINT [DF__Component__Sourc__6C190EBB] DEFAULT (getdate()) NULL,
    [SourceDateModified]     DATETIME        NULL,
    CONSTRAINT [PK_ComponetScore] PRIMARY KEY CLUSTERED ([ComponentScoreID] ASC)
);

