CREATE TABLE [dbo].[FactSSMCopy] (
    [UserID]                 BIGINT          NULL,
    [TestAttemptID]          INT             NOT NULL,
    [FirstName]              VARCHAR (32)    NULL,
    [LastName]               VARCHAR (32)    NULL,
    [UserName]               VARCHAR (50)    NULL,
    [ConsortiumID]           BIGINT          NULL,
    [Consortiumname]         VARCHAR (128)   NULL,
    [InstitutionID]          BIGINT          NULL,
    [InstitutionName]        VARCHAR (128)   NULL,
    [ProgramTypeID]          INT             NULL,
    [ProgramTypeName]        VARCHAR (64)    NULL,
    [ContentAreaID]          INT             NULL,
    [ActiveClassID]          BIGINT          NULL,
    [ActiveClassName]        VARCHAR (45)    NULL,
    [TestingClassID]         BIGINT          NULL,
    [TestingClassName]       VARCHAR (45)    NULL,
    [AssessmentID]           INT             NULL,
    [AssessmentDateTime]     SMALLDATETIME   NULL,
    [AssessmentName]         VARCHAR (128)   NULL,
    [ContentAreaName]        VARCHAR (128)   NULL,
    [AdjPercentage]          DECIMAL (12, 2) NULL,
    [SSMScore]               DECIMAL (6, 3)  NULL,
    [ScoreCategoryID]        INT             NULL,
    [ScoreCategoryName]      NVARCHAR (40)   NULL,
    [ScoreCategoryMessage]   VARCHAR (30)    NULL,
    [ProgramMean]            DECIMAL (12, 2) NULL,
    [TestAttempt]            BIGINT          NULL,
    [PendingAssessmentCount] INT             NOT NULL,
    [IsFinalScore]           BIT             NOT NULL,
    [IsLatestSSMScore]       INT             NOT NULL,
    [IsActive]               INT             NOT NULL,
    [DateCreated]            SMALLDATETIME   NULL,
    [UserCreated]            VARCHAR (30)    NULL,
    [DateModified]           SMALLDATETIME   NULL,
    [UserModified]           VARCHAR (30)    NULL,
    [SourceSystemID]         INT             NOT NULL,
    [SourceDateCreated]      SMALLDATETIME   NULL,
    [BatchID]                INT             NULL
);

